# Gitleaks configuration for secret detection

[allowlist]
description = "Global allowlist"
regexes = [
  '''mock-hash-\d+''',
  '''cs_test_''',
  '''process\.env\.[A-Z_]+''',
  '''NEXT_PUBLIC_[A-Z_]+'''
]

# Custom rules for common API keys
[[rules]]
id = "stripe-secret-key"
description = "Stripe Secret Key"
regex = '''sk_live_[0-9a-zA-Z]{24,}'''
tags = ["key", "stripe"]

[[rules]]
id = "sendgrid-api-key"
description = "SendGrid API Key"
regex = '''SG\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9_-]{43}'''
tags = ["key", "sendgrid"]

[[rules]]
id = "datadog-api-key"
description = "Datadog API Key"
regex = '''DD[a-zA-Z0-9]{32}'''
tags = ["key", "datadog"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''['"']?[Aa][Pp][Ii][_-]?[Kk][Ee][Yy]['"']?\s*[:=]\s*['"'][0-9a-zA-Z]{32,}['"']'''
tags = ["key", "api"]

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''['"']?[Ss][Ee][Cc][Rr][Ee][Tt][_-]?[Kk][Ee][Yy]['"']?\s*[:=]\s*['"'][0-9a-zA-Z]{32,}['"']'''
tags = ["key", "secret"]