// app/legal/privacy/page.tsx
import React from 'react'
import { LegalPageLayout } from '@/components/legal/LegalPageLayout'

export default function PrivacyPolicyPage() {
  return (
    <LegalPageLayout title="Privacy Policy">
      <h3 className="text-[24px] font-light mt-8 mb-4">1.1 Scope</h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        This Privacy Policy explains how Entrainment Inc., doing business as{' '}
        <strong>Anthrasite</strong> ("Anthrasite," "we," "our," or "us"),
        collects, uses, and discloses information when you visit{' '}
        <strong>anthrasite.io</strong> or purchase our website‑audit services
        (the "Services"). This policy applies to residents of the United States.
      </p>

      <h3 className="text-[24px] font-light mt-8 mb-4">
        1.2 Information We Collect
      </h3>
      <table className="w-full mb-6 text-[17px]">
        <thead>
          <tr className="border-b border-white/20">
            <th className="text-left py-3 font-medium">Category</th>
            <th className="text-left py-3 font-medium">Examples</th>
            <th className="text-left py-3 font-medium">Source</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-white/10">
            <td className="py-3">
              <strong>Information you provide</strong>
            </td>
            <td className="py-3 opacity-80">
              Name, business email, billing address, payment method, URLs you
              ask us to analyze, support requests, survey responses
            </td>
            <td className="py-3 opacity-80">Directly from you</td>
          </tr>
          <tr className="border-b border-white/10">
            <td className="py-3">
              <strong>Automatic usage data</strong>
            </td>
            <td className="py-3 opacity-80">
              IP address, device/browser type, referring pages, pages viewed,
              time spent, error logs
            </td>
            <td className="py-3 opacity-80">
              Collected through cookies, log files, and similar technologies
            </td>
          </tr>
          <tr className="border-b border-white/10">
            <td className="py-3">
              <strong>Session recordings</strong>
            </td>
            <td className="py-3 opacity-80">
              Mouse movements, clicks, scrolls, and anonymized page content on
              certain pages (e.g., landing pages)
            </td>
            <td className="py-3 opacity-80">
              Collected via Microsoft Clarity for UX analysis; IP addresses are
              masked
            </td>
          </tr>
          <tr className="border-b border-white/10">
            <td className="py-3">
              <strong>Derived analytics</strong>
            </td>
            <td className="py-3 opacity-80">
              Site‑performance metrics, audit scores, uplift estimates
            </td>
            <td className="py-3 opacity-80">
              Generated by our assessment engine from the URLs you submit
            </td>
          </tr>
        </tbody>
      </table>

      <h3 className="text-[24px] font-light mt-8 mb-4">
        1.3 How We Use Information
      </h3>
      <ol className="list-decimal pl-6 text-[17px] opacity-80 space-y-2 mb-6">
        <li>
          <strong>Deliver and improve the Services</strong> (run audits,
          generate reports, provide support)
        </li>
        <li>
          <strong>Process transactions</strong> and send invoices/receipts
        </li>
        <li>
          <strong>Communicate</strong> – service alerts, feature updates,
          marketing (with opt‑out)
        </li>
        <li>
          <strong>Research & development</strong> – aggregate, de‑identified
          data to refine scoring models
        </li>
        <li>
          <strong>Legal & security</strong> – detect fraud, enforce Terms,
          comply with applicable laws
        </li>
      </ol>

      <h3 className="text-[24px] font-light mt-8 mb-4">
        1.4 How We Share Information
      </h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        We may share information with the following categories of third parties:
      </p>
      <ul className="list-disc pl-6 text-[17px] opacity-80 space-y-2 mb-6">
        <li>
          <strong>Service providers</strong> – such as payment processors
          (Stripe), cloud hosting providers (Vercel, Supabase), analytics
          providers (PostHog), and session recording tools (Microsoft Clarity),
          who are contractually bound to protect the data. For a full list, see
          our <a href="/legal/subprocessors">Subprocessor List</a>.
        </li>
        <li>
          <strong>Corporate events</strong> – in connection with a merger,
          acquisition, or asset sale.
        </li>
        <li>
          <strong>Legal compliance</strong> – when required by law, court order,
          or to protect our rights, property, or safety.
        </li>
        <li>
          We <strong>do not sell or share</strong> personal information for
          monetary value, though some analytics usage may be considered
          "sharing" under CPRA, which you can opt out of.
        </li>
      </ul>

      <h3 className="text-[24px] font-light mt-8 mb-4">1.5 Data Retention</h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        We retain personal data for as long as necessary to fulfill the purposes
        for which it was collected. Our retention periods are as follows:
      </p>
      <ul className="list-disc pl-6 text-[17px] opacity-80 space-y-2 mb-6">
        <li>
          <strong>Payment and invoice records</strong>: 7 years for tax and
          accounting compliance.
        </li>
        <li>
          <strong>Lead data and waitlist entries</strong>: 12 months, or until
          our service launches and you are notified.
        </li>
        <li>
          <strong>Analytics logs</strong>: 14-18 months.
        </li>
        <li>
          <strong>Support and privacy requests</strong>: 24 months for our audit
          trail.
        </li>
      </ul>

      <h3 className="text-[24px] font-light mt-8 mb-4">1.6 Security</h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        We implement industry-standard security measures, including encryption
        in transit (TLS 1.2+), least‑privilege access controls, and encrypted
        backups. However, no method of transmission over the Internet is 100%
        secure.
      </p>

      <h3 className="text-[24px] font-light mt-8 mb-4">
        1.7 Your Consumer Privacy Rights
      </h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        Depending on your state of residence (e.g., California, Colorado,
        Virginia), you may have the right to:
      </p>
      <ul className="list-disc pl-6 text-[17px] opacity-80 space-y-2 mb-6">
        <li>
          <strong>Know</strong> what personal information we collect, use, and
          disclose.
        </li>
        <li>
          <strong>Access and receive a copy</strong> of your personal
          information.
        </li>
        <li>
          <strong>Delete</strong> your personal information, subject to certain
          exceptions.
        </li>
        <li>
          <strong>Correct</strong> inaccurate personal information.
        </li>
        <li>
          <strong>Opt out</strong> of the "sale" or "sharing" of your personal
          information, which you can do on our{' '}
          <a href="/legal/do-not-sell">Do Not Sell or Share</a> page.
        </li>
      </ul>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        To exercise these rights, please submit a request by emailing{' '}
        <strong>privacy@anthrasite.io</strong> or by using our online request
        form if available. We will respond within 45 days. We will verify your
        request by asking you to confirm it from the email address associated
        with your data.
      </p>

      <h3 className="text-[24px] font-light mt-8 mb-4">
        1.8 Children's Privacy
      </h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        Our Services are not directed to children under the age of 13, and we do
        not knowingly collect personal information from them.
      </p>

      <h3 className="text-[24px] font-light mt-8 mb-4">
        1.9 Changes to This Policy
      </h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        We may update this Privacy Policy from time to time. We will notify you
        of any material changes by posting the new policy on this page and
        updating the "Last updated" date.
      </p>

      <h3 className="text-[24px] font-light mt-8 mb-4">1.10 Contact Us</h3>
      <p className="text-[17px] opacity-80 leading-relaxed mb-6">
        If you have any questions about this Privacy Policy, please contact us
        at:
        <br />
        Email: <strong>privacy@anthrasite.io</strong>
        <br />
        Mail: Entrainment Inc., 99 Madison Ave #1234, New York, NY 10016, USA
      </p>
    </LegalPageLayout>
  )
}
